import Header from "@/components/header";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import Footer from "@/components/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${poppins.variable}  !px-16  max-sm:!px-0 `}
    >
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
